web:
  extends:
    file: ../common.yml
    service: web
  environment:
    - TITLE=PRODUCTION
    - "constraint:environment==production"
  labels:
  - "com.example.description=Awesome webapp"
  - "com.example.department=IT"
